workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60

    environment:
      # از Java 11 استفاده می‌کنیم چون به‌طور پیش‌فرض روی Codemagic موجود است
      java: 11

      # نصب خودکار Android SDK
      android:
        api-level: "34"
        build-tools: "34.0.0"
        ndk: "21.4.7075529"

    scripts:
      - name: Debug Java version
        script: |
          java -version
          echo "JAVA_HOME=$JAVA_HOME"

      - name: Ensure Gradle wrapper is executable
        script: |
          chmod +x ./gradlew

      - name: Clean
        script: |
          ./gradlew clean --no-daemon --stacktrace

      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
