workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17

    scripts:
      - name: Set executable permission for Gradle wrapper
        script: chmod +x ./gradlew

      - name: Create dummy google-services.json (safe for debug)
        script: |
          mkdir -p app
          cat > app/google-services.json << 'EOF'
          {
            "project_info": {
              "project_number": "0",
              "project_id": "dummy-project",
              "storage_bucket": "dummy.appspot.com"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:0:android:dummy",
                  "android_client_info": { "package_name": "com.example.persianaiapp" }
                },
                "oauth_client": [],
                "api_key": [{ "current_key": "DUMMY" }],
                "services": {
                  "appinvite_service": { "other_platform_oauth_client": [] }
                }
              }
            ],
            "configuration_version": "1"
          }
          EOF

      - name: Clean Gradle cache
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
