workflows:
  build-with-aar:
    name: Build APK + AAR
    environment:
      java: 17
      android: sdk-34

    scripts:
      - name: Set up local.properties
        script: echo "sdk.dir=$ANDROID_HOME" > "$CM_BUILD_DIR/local.properties"

      - name: Create dummy google-services.json
        script: |
          mkdir -p app/
          echo '{
            "project_info": {
              "project_number": "123456789",
              "project_id": "dummy-project"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:123456789:android:dummy",
                  "android_client_info": {
                    "package_name": "com.example.persianaiapp"
                  }
                }
              }
            ]
          }' > app/google-services.json

      - name: Make gradlew executable
        script: chmod +x gradlew

      - name: Clean Gradle cache
        script: ./gradlew clean --no-daemon

      - name: Build APK and AAR
        script: ./gradlew :app:assembleDebug :voskandroid:assembleRelease --no-daemon

    artifacts:
      - app/build/outputs/**/*.apk
      - voskandroid/build/outputs/**/*.aar

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
