workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 90

    environment:
      # استفاده از Java 11 (موجود به‌طور پیش‌فرض روی Codemagic)
      java: openjdk11

      # نصب خودکار Android SDK components
      android:
        api-level: "34"
        build-tools: "34.0.0"
        ndk: "21.4.7075529"

    scripts:
      - name: Ensure Gradle wrapper is executable
        script: chmod +x ./gradlew

      - name: Clean and assembleDebug
        script: ./gradlew clean assembleDebug --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - you@domain.com
        notify:
          success: true
          failure: true
