workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60

    environment:
      # فقط نسخه Java 11 (پیش‌فرض Codemagic)
      java: 11

    scripts:
      - name: Debug environment
        script: |
          echo "===== Java Info ====="
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "===== SDK Info ====="
          sdkmanager --list

      - name: Ensure Gradle wrapper executable
        script: chmod +x ./gradlew

      - name: Install Android SDK components
        script: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "ndk;21.4.7075529"

      - name: Create dummy google-services.json if missing
        script: |
          if [ ! -f app/google-services.json ]; then
            mkdir -p app
            echo '{}' > app/google-services.json
          fi

      - name: Clean and assembleDebug
        script: ./gradlew clean assembleDebug --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - you@domain.com
        notify:
          success: true
          failure: true
