workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Clean Gradle cache
        script: ./gradlew clean
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
