workflows:
  android-workflow:
    name: Persian AI Assistant Build
    max_build_duration: 90
    environment:
      jdk: 11
    scripts:
      - name: Set up Gradle
        script: |
          chmod +x ./gradlew
          ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleDebug --no-daemon --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - example@gmail.com
        notify:
          success: true
          failure: true
