workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 90
    environment:
      jdk: 11
    scripts:
      - name: Ensure Gradle wrapper is executable
        script: chmod +x ./gradlew
      - name: Clean and assembleDebug
        script: ./gradlew clean assembleDebug --no-daemon --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
