workflows:
  simple-apk:
    name: Simple APK Build
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      java: "17"
      vars:
        PACKAGE_NAME: "com.example.persianaiapp"
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.android/build-cache
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_HOME" > "$CM_BUILD_DIR/local.properties"
      - name: Build debug APK
        script: |
          chmod +x ./gradlew
          ./gradlew clean assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - ghadir.baraty@gmail.com
        notify:
          success: true
          failure: true

  android-workflow:
    name: Android Full Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      java: "17"
      vars:
        PACKAGE_NAME: "com.example.persianaiapp"
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ~/.android/build-cache
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_HOME" > "$CM_BUILD_DIR/local.properties"
      - name: Build release APK
        script: |
          chmod +x ./gradlew
          ./gradlew clean assembleRelease --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - ghadir.baraty@gmail.com
        notify:
          success: true
          failure: true
