workflows:
  debug-build:
    name: Debug Build Free
    environment:
      java: 17

    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_HOME" > "$CM_BUILD_DIR/local.properties"

      - name: Create dummy google-services.json
        script: |
          mkdir -p app/
          echo '{
            "project_info": {
              "project_number": "123456789",
              "project_id": "dummy-project"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:123456789:android:dummy",
                  "android_client_info": {
                    "package_name": "com.example.persianaiapp"
                  }
                }
              }
            ]
          }' > app/google-services.json

      - name: Clean Gradle cache (اختیاری برای رفع خطاهای کش)
        script: |
          ./gradlew clean --no-daemon

      - name: Build debug APK
        script: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace --no-daemon

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com # ایمیل خودتون رو بذارید
        notify:
          success: true
          failure: true
