workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      java: 17
      vars:
        PACKAGE_NAME: "com.example.persianaiapp"
        GOOGLE_PLAY_TRACK: alpha
    scripts:
      - name: Set Android SDK
        script: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34"
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_HOME" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release
        script: |
          LATEST_GOOGLE_PLAY_VERSION_CODE=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z "$LATEST_GOOGLE_PLAY_VERSION_CODE" ]; then
              # fallback in case no build number was found from google play
              UPDATED_VERSION_CODE=$BUILD_NUMBER
          else
              UPDATED_VERSION_CODE=$(($LATEST_GOOGLE_PLAY_VERSION_CODE + 1))
          fi
          cd android
          ./gradlew bundleRelease \
            -PversionCode=$UPDATED_VERSION_CODE \
            -PversionName=1.0.$UPDATED_VERSION_CODE
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
