workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17

    scripts:
      - name: Ensure Gradle wrapper is executable
        script: chmod +x ./gradlew

      - name: Create empty google-services.json if missing
        script: |
          if [ ! -f app/google-services.json ]; then
            mkdir -p app
            echo '{}' > app/google-services.json
          fi

      - name: Clean
        script: ./gradlew clean --no-daemon --stacktrace

      - name: Build Debug APK
        script: ./gradlew assembleDebug --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
