workflows:
  android-simple:
    name: Android Simple Build
    environment:
      java: "17"
    scripts:
      - name: Set up environment
        script: |
          echo "sdk.dir=$ANDROID_HOME" > "$CM_BUILD_DIR/local.properties"
          chmod +x ./gradlew
      - name: Build APK
        script: |
          ./gradlew clean assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
