workflows:
  android-build:
    name: Android Build
    max_build_duration: 60

    environment:
      # حتماً از Java 11 (openjdk11) استفاده می‌کنیم
      java: openjdk11

      # تنظیم خودکار SDK برای اندروید ۳۴
      android:
        api-level: "34"
        build-tools: "34.0.0"
        ndk: "21.4.7075529"

    scripts:
      - name: Debug Java version
        script: |
          echo "===== Java Info ====="
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          echo "====================="

      - name: Ensure Gradle wrapper executable
        script: chmod +x ./gradlew

      - name: Clean project
        script: ./gradlew clean --no-daemon --stacktrace

      - name: Build Debug APK
        script: ./gradlew assembleDebug --no-daemon --stacktrace

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - your@email.com
        notify:
          success: true
          failure: true
