workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 90
    environment:
      java: openjdk11
      android:
        api-level: 34
        build-tools: 34.0.0
        ndk: 21.4.7075529
    scripts:
      - name: Ensure Gradle wrapper is executable
        script: chmod +x ./gradlew
      - name: Clean and assembleDebug
        script: ./gradlew clean assembleDebug --no-daemon --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
