workflows:
  debug-build:
    name: Debug Build (Simple)
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      java: 17
    scripts:
      - name: Set up Android SDK
        script: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platforms;android-34"
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_HOME" > "$CM_BUILD_DIR/local.properties"
      - name: Create dummy google-services.json
        script: |
          mkdir -p app/
          echo '{
            "project_info": {
              "project_number": "123456789",
              "project_id": "dummy-project"
            },
            "client": [
              {
                "client_info": {
                  "mobilesdk_app_id": "1:123456789:android:dummy",
                  "android_client_info": {
                    "package_name": "com.example.persianaiapp"
                  }
                }
              }
            ]
          }' > app/google-services.json
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com  # ایمیل خودتون رو بذارید
        notify:
          success: true
          failure: true
