#!/bin/bash
# Persian AI Assistant - Build Monitor Script
# This script monitors builds across all platforms

echo "=== Persian AI Assistant Build Monitor ==="
echo "Monitoring builds across all platforms..."
echo ""

# Configuration
GITHUB_REPO="ghadirb/PersianAIAssistant"
GITHUB_TOKEN="${GITHUB_TOKEN:-<SET_VIA_ENV>}"
CODEMAGIC_TOKEN="${CODEMAGIC_TOKEN:-<SET_VIA_ENV>}"
GITLAB_TOKEN="${GITLAB_TOKEN:-<SET_VIA_ENV>}"

echo "🔗 DIRECT MONITORING LINKS:"
echo "=========================="
echo ""
echo "📊 GitHub Actions:"
echo "https://github.com/$GITHUB_REPO/actions"
echo ""
echo "🔧 CodeMagic Dashboard:"
echo "https://codemagic.io/"
echo "(Login with token: $CODEMAGIC_TOKEN)"
echo ""
echo "🐙 GitLab (Alternative):"
echo "https://gitlab.com"
echo "(Use token: $GITLAB_TOKEN)"
echo ""
echo "📱 APK Download Links (when builds complete):"
echo "- GitHub: https://github.com/$GITHUB_REPO/actions (Artifacts section)"
echo "- CodeMagic: Check email at ghadir.baraty@gmail.com"
echo "- GitLab: Repository page -> CI/CD -> Jobs"
echo ""

echo "🚀 QUICK ACTIONS:"
echo "=================="
echo ""
echo "1. Push to GitHub:"
echo "   git push https://$GITHUB_TOKEN@github.com/$GITHUB_REPO.git main"
echo ""
echo "2. Trigger GitHub Workflow:"
echo "   curl -X POST -H \"Authorization: token $GITHUB_TOKEN\" \\"
echo "        -H \"Accept: application/vnd.github.v3+json\" \\"
echo "        https://api.github.com/repos/$GITHUB_REPO/actions/workflows/fixed-build.yml/dispatches \\"
echo "        -d '{\"ref\":\"main\"}'"
echo ""
echo "3. Check GitHub Build Status:"
echo "   curl -H \"Authorization: token $GITHUB_TOKEN\" \\"
echo "        https://api.github.com/repos/$GITHUB_REPO/actions/runs"
echo ""

echo "📋 MANUAL STEPS:"
echo "=================="
echo "1. Open https://github.com/$GITHUB_REPO/actions"
echo "2. Click 'Persian AI Assistant - Fixed Build'"
echo "3. Click 'Run workflow' -> Select 'debug'"
echo "4. Wait 5-10 minutes"
echo "5. Download APK from 'Artifacts' section"
echo ""
echo "6. For CodeMagic: Go to https://codemagic.io/"
echo "7. Login with token: $CODEMAGIC_TOKEN"
echo "8. Start new build"
echo "9. Check email for APK"
echo ""

echo "✅ Build monitoring guide created!"
echo ""
echo "Copy and paste the URLs above into your browser to monitor builds directly."
