name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=4 -Dorg.gradle.parallel=true"
  JAVA_OPTS: "-Xmx4g -Xms1g"
  ANDROID_HOME: /usr/local/lib/android/sdk
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        build-tools-version: '34.0.0'
        ndk-version: '25.1.8937393'
        cmake-version: '3.22.1'

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Cache Android
      uses: actions/cache@v4
      with:
        path: |
          ~/.android/build-cache
          ~/.android/lint-cache
        key: ${{ runner.os }}-android-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-android-

    - name: Build with Gradle
      run: |
        ./gradlew --no-daemon --stacktrace --scan \
          -Dorg.gradle.parallel=true \
          -Dorg.gradle.caching=true \
          -Dorg.gradle.configureondemand=true \
          build
      env:
        ORG_GRADLE_PROJECT_androidxComposeCompiler_reportUndefined: false
        ORG_GRADLE_PROJECT_androidxComposeCompiler_suppressKotlinVersionCompatibilityCheck: true

    - name: Upload APK
      if: success() && github.event_name == 'push' && !contains(github.ref, 'pull/')
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: app/build/outputs/apk/**/*.apk
        retention-days: 7

    - name: Upload mapping file
      if: success() && github.event_name == 'push' && !contains(github.ref, 'pull/')
      uses: actions/upload-artifact@v4
      with:
        name: mapping
        path: app/build/outputs/mapping/**/mapping.txt
        retention-days: 7

    - name: Build Summary
      if: always()
      run: |
        echo "### Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Status:** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Number:** ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Triggered by:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
