name: Android Debug Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android SDK Build-Tools and Platform
        uses: android-actions/setup-android@v3
        with:
          packages: |-
            platforms;android-34
            build-tools;33.0.1

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew clean assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
